# Flask Server logging configuration

version: 1

disable_existing_loggers: true

formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  console:
    class: server.logging_utils.CustomFormatter
  error:
    format: '%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: console
    stream: ext://sys.stdout

  info_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: default
    filename: ./logs/info.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: error
    filename: ./logs/errors.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

root:
  level: INFO
  handlers: [console, info_file, error_file]
