"""profile attr unique constraint

Revision ID: 43e4f7a14985
Revises: 7ff9c8b09bf5
Create Date: 2022-05-21 19:48:18.815846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "43e4f7a14985"
down_revision = "7ff9c8b09bf5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unique_key_per_profile", "profile_attribute", ["profile_id", "key"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "profile_attribute_id_key_key", "profile_attribute", ["id", "key"]
    )
    # ### end Alembic commands ###
