"""added profile birth column

Revision ID: 7ff9c8b09bf5
Revises: 49408a499348
Create Date: 2022-05-21 18:11:53.094410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7ff9c8b09bf5"
down_revision = "49408a499348"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("profile", sa.Column("birth", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profile", "birth")
    # ### end Alembic commands ###
