"""add photo sha256 hash

Revision ID: b36ae5ea183b
Revises: 90df42292155
Create Date: 2022-05-21 14:17:28.008721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b36ae5ea183b"
down_revision = "90df42292155"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("photo", sa.Column("sha256_hash", sa.String(), nullable=True))
    op.create_unique_constraint("photo_sha256_hash_key", "photo", ["sha256_hash"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("photo_sha256_hash_key", "photo", type_="unique")
    op.drop_column("photo", "sha256_hash")
    # ### end Alembic commands ###
