"""remove circular reference

Revision ID: fef17bd5b83b
Revises: 7c6f38b03983
Create Date: 2022-05-24 02:08:09.604488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "fef17bd5b83b"
down_revision = "7c6f38b03983"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("profile_thumbnail_id_fkey", "profile", type_="foreignkey")
    op.drop_column("profile", "thumbnail_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profile",
        sa.Column(
            "thumbnail_id", postgresql.UUID(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "profile_thumbnail_id_fkey", "profile", "face", ["thumbnail_id"], ["id"]
    )
    # ### end Alembic commands ###
