"""profile attributes key and value

Revision ID: 49408a499348
Revises: b36ae5ea183b
Create Date: 2022-05-21 18:09:22.569243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49408a499348'
down_revision = 'b36ae5ea183b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_attribute', sa.Column('key', sa.String(length=30), nullable=False))
    op.add_column('profile_attribute', sa.Column('value', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_attribute', 'value')
    op.drop_column('profile_attribute', 'key')
    # ### end Alembic commands ###
