name: Run pytests
on: [push]

jobs:
  pytests-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: "facial-recognition-test"
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      id: setup-python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Cache virtual environment
      uses: actions/cache@v3
      with:
        path: |
          ~/.local/share/virtualenvs
          .tox/py38/.pytest_cache
        key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }}
    - name: Cache facial recognition models
      uses: actions/cache@v3
      with:
        path: "public/models"
        key: buffalo_l_2022_05_24
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv tox
        pipenv install --dev
    - name: Run tests
      run: |
        pipenv run pytest
      env:
        DB_HOST: localhost
        DB_PORT: 5432
        DB_NAME: facial-recognition
        DB_USERNAME: postgres
        DB_PASSWORD: postgres
