name: Run pytests
on: [push]

jobs:
  postgres-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: test_db
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv tox tox-gh-actions
    - name: Test with tox
      run: tox
      env:
        DB_HOST: postgres
        DB_PORT: 5432
        DB_NAME: test_db
        DB_USERNAME: postgres
        DB_PASSWORD: postgres
        FLASK_APP: wsgi:app
        FLASK_ENV: development
